### ISSUE TITLE
Pip installation missing yaw_optimization

### ISSUE THREAD

**Issue by rafmudaf** [NREL/floris#362]
### Discussed in https://github.com/NREL/floris/discussions/360

<div type='discussions-op-text'>

<sup>Originally posted by **mr483** March  3, 2022</sup>
I have installed FLORIS 3.0 via pip, but my install seems to be missing the "yaw_optimization" module which should be located at floris.tools.optimization. I noticed this when the import failed while running example 09. When checking the source code, I notice the yaw_optimization folder is missing. I tried to reinstall on a separate environment and experience the same issue. I noticed this folder seems to not have an __init__ file in it, which may be causing the issue. </div>

**Comment by rafmudaf** [comment]
@mr483 I think this is fixed by #370. Could you upgrade and verify?

**Comment by mr483** [comment]
@rafmudaf , I created a new env. and ran pip install. I see in the source that your change from #370 is represented in the optimization/__init__.py file, but the yaw_optimization folder still does not exist in the source when installed by pip. 

I thought it was necessary to include an init file in the yaw_optimization folder as well, so pip recognizes folder this as part of the package? I think this should solve the problem.
